### ISSUE TITLE
A.solve() cause Cannot read property 'set' of undefined

### ISSUE THREAD

**Issue by linonetwo** [gumm/dag-solve#2]
Why I can't ```A.solve();```?

```js
const DAG = require('dag-solve');

const g = new DAG();
const A = g.makeNode('A').setMath('($1 + $2) / $3')
const B = g.makeNode('B')
const C = g.makeNode('C')
const D = g.makeNode('D')

g.connect(A, g.root);
// B -> A
g.connect(B, A);
// C -> A
g.connect(C, A);
// D -> A
g.connect(D, A);

B.setMath(9);
C.setMath(6);
D.setMath(3);
```
Will cause 
```
TypeError: Cannot read property 'set' of undefined
    at Node.solve (dag-solve/main.js:920:19)
    at Node.solve (dag-solve/main.js:925:19)
```
While ```g.solve()``` will give ```5``` which is correct.

What should I do if I need the intermediate value?

**Comment by gumm** [comment]
You can not call solve directly on a node. In order for a node to solve, it needs the solution from each preceding node (in topological order) to be able to solve itself. In isolation, this data is not available.

If however, you want to see what the values are at each node, you can use `g.debug()`

in your case:
```
g.debug()
Map {
  'topoIds' => [ 4, 3, 2, 1, 0 ],
  'data' => undefined,
  4 => 3,
  3 => 6,
  2 => 9,
  1 => 5,
  0 => 5 }
```
This maps the ID of each node to the solution of that node.

**Comment by linonetwo** [comment]
Thanks, got it.
